spring.application.name=bar-management-backend
server.port=8081


# ==========================================
# DATABASE CONFIGURATION
# ==========================================

spring.datasource.url=jdbc:mysql://localhost:3306/bar_db
spring.datasource.username=root
spring.datasource.password=9594151506
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ==========================================
# JPA / HIBERNATE CONFIGURATION
# ==========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ==========================================
# JWT CONFIGURATION
# ==========================================

jwt.secret=BarManagementSystemDevelopmentSecretKey2026VeryLongRandomValue
jwt.expiration=86400000